<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LowonganMagangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'judul'                => 'Magang Front-End Developer',
                'deskripsi'            => 'Bekerja sebagai pengembang antarmuka pengguna web dengan HTML, CSS, dan JavaScript.',
                'tanggal_mulai_magang' => now()->addDays(10),
                'deadline_lowongan'    => now()->addDays(5),
                'lokasi'               => 'Jakarta',
                'perusahaan_id'        => 1,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_frontend.pdf',
                'status'               => 'aktif',
                'gaji'                 => 3000000,
                'kuota'                => 3,
            ],
            [
                'judul'                => 'Magang Back-End Developer',
                'deskripsi'            => 'Mengembangkan API dan mengelola database menggunakan PHP/Laravel.',
                'tanggal_mulai_magang' => now()->addDays(20),
                'deadline_lowongan'    => now()->addDays(10),
                'lokasi'               => 'Jakarta',
                'perusahaan_id'        => 1,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_backend.pdf',
                'status'               => 'aktif',
                'gaji'                 => 3500000,
                'kuota'                => 2,
            ],
            [
                'judul'                => 'Magang Data Analyst',
                'deskripsi'            => 'Analisis data perusahaan dan membuat laporan visualisasi menggunakan Python.',
                'tanggal_mulai_magang' => now()->addDays(15),
                'deadline_lowongan'    => now()->addDays(7),
                'lokasi'               => 'Yogyakarta',
                'perusahaan_id'        => 2,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_data_analyst.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2800000,
                'kuota'                => 4,
            ],
            [
                'judul'                => 'Magang UI/UX Designer',
                'deskripsi'            => 'Membantu mendesain antarmuka dan pengalaman pengguna untuk aplikasi web/mobile.',
                'tanggal_mulai_magang' => now()->addDays(25),
                'deadline_lowongan'    => now()->addDays(12),
                'lokasi'               => 'Yogyakarta',
                'perusahaan_id'        => 2,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_uiux.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2500000,
                'kuota'                => 2,
            ],
            [
                'judul'                => 'Magang Mobile Developer',
                'deskripsi'            => 'Pengembangan aplikasi Android menggunakan Kotlin.',
                'tanggal_mulai_magang' => now()->addDays(18),
                'deadline_lowongan'    => now()->addDays(9),
                'lokasi'               => 'Bandung',
                'perusahaan_id'        => 3,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_mobile_dev.pdf',
                'status'               => 'aktif',
                'gaji'                 => 3200000,
                'kuota'                => 3,
            ],
            [
                'judul'                => 'Magang DevOps Engineer',
                'deskripsi'            => 'Mempelajari dan membantu pengelolaan infrastruktur CI/CD di AWS.',
                'tanggal_mulai_magang' => now()->addDays(30),
                'deadline_lowongan'    => now()->addDays(20),
                'lokasi'               => 'Bandung',
                'perusahaan_id'        => 3,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_devops.pdf',
                'status'               => 'aktif',
                'gaji'                 => 4000000,
                'kuota'                => 2,
            ],
            [
                'judul'                => 'Magang Data Engineer',
                'deskripsi'            => 'Mengolah pipeline data menggunakan ETL dan SQL.',
                'tanggal_mulai_magang' => now()->addDays(12),
                'deadline_lowongan'    => now()->addDays(6),
                'lokasi'               => 'Surabaya',
                'perusahaan_id'        => 4,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_data_engineer.pdf',
                'status'               => 'aktif',
                'gaji'                 => 3100000,
                'kuota'                => 3,
            ],
            [
                'judul'                => 'Magang Social Media Specialist',
                'deskripsi'            => 'Mengelola konten dan kampanye media sosial perusahaan.',
                'tanggal_mulai_magang' => now()->addDays(22),
                'deadline_lowongan'    => now()->addDays(11),
                'lokasi'               => 'Surabaya',
                'perusahaan_id'        => 4,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_sosmed.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2300000,
                'kuota'                => 4,
            ],
            [
                'judul'                => 'Magang Business Analyst',
                'deskripsi'            => 'Menganalisis kebutuhan bisnis dan membuat dokumentasi proses.',
                'tanggal_mulai_magang' => now()->addDays(14),
                'deadline_lowongan'    => now()->addDays(8),
                'lokasi'               => 'Semarang',
                'perusahaan_id'        => 5,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_business_analyst.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2900000,
                'kuota'                => 2,
            ],
            [
                'judul'                => 'Magang Graphic Designer',
                'deskripsi'            => 'Membuat materi visual dan branding untuk klien.',
                'tanggal_mulai_magang' => now()->addDays(17),
                'deadline_lowongan'    => now()->addDays(10),
                'lokasi'               => 'Semarang',
                'perusahaan_id'        => 5,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_graphic_designer.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2400000,
                'kuota'                => 3,
            ],
            [
                'judul'                => 'Magang Sales & Marketing',
                'deskripsi'            => 'Membantu tim sales melakukan riset pasar dan strategi pemasaran.',
                'tanggal_mulai_magang' => now()->addDays(11),
                'deadline_lowongan'    => now()->addDays(5),
                'lokasi'               => 'Medan',
                'perusahaan_id'        => 6,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_sales_marketing.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2200000,
                'kuota'                => 4,
            ],
            [
                'judul'                => 'Magang Customer Service',
                'deskripsi'            => 'Menangani pertanyaan pelanggan dan meningkatkan kepuasan layanan.',
                'tanggal_mulai_magang' => now()->addDays(21),
                'deadline_lowongan'    => now()->addDays(13),
                'lokasi'               => 'Medan',
                'perusahaan_id'        => 6,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_customer_service.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2100000,
                'kuota'                => 5,
            ],
            [
                'judul'                => 'Magang AI Research Assistant',
                'deskripsi'            => 'Membantu penelitian AI dan prototyping model machine learning.',
                'tanggal_mulai_magang' => now()->addDays(16),
                'deadline_lowongan'    => now()->addDays(8),
                'lokasi'               => 'Bandung',
                'perusahaan_id'        => 7,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_ai_research.pdf',
                'status'               => 'aktif',
                'gaji'                 => 3800000,
                'kuota'                => 2,
            ],
            [
                'judul'                => 'Magang Software Tester',
                'deskripsi'            => 'Melakukan pengujian sistem dan pelaporan bug untuk tim QA.',
                'tanggal_mulai_magang' => now()->addDays(26),
                'deadline_lowongan'    => now()->addDays(15),
                'lokasi'               => 'Bandung',
                'perusahaan_id'        => 7,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_software_tester.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2700000,
                'kuota'                => 3,
            ],
            [
                'judul'                => 'Magang Video Editor',
                'deskripsi'            => 'Mengedit video promosi dan konten sosial media.',
                'tanggal_mulai_magang' => now()->addDays(13),
                'deadline_lowongan'    => now()->addDays(6),
                'lokasi'               => 'Yogyakarta',
                'perusahaan_id'        => 8,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_video_editor.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2300000,
                'kuota'                => 3,
            ],
            [
                'judul'                => 'Magang Animator',
                'deskripsi'            => 'Membuat animasi untuk iklan dan konten digital.',
                'tanggal_mulai_magang' => now()->addDays(23),
                'deadline_lowongan'    => now()->addDays(12),
                'lokasi'               => 'Yogyakarta',
                'perusahaan_id'        => 8,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_animator.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2600000,
                'kuota'                => 2,
            ],
            [
                'judul'                => 'Magang R&D Engineer',
                'deskripsi'            => 'Mengembangkan prototipe dan melakukan eksperimen teknologi baru.',
                'tanggal_mulai_magang' => now()->addDays(19),
                'deadline_lowongan'    => now()->addDays(9),
                'lokasi'               => 'Jakarta',
                'perusahaan_id'        => 9,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_rnd_engineer.pdf',
                'status'               => 'aktif',
                'gaji'                 => 3700000,
                'kuota'                => 2,
            ],
            [
                'judul'                => 'Magang IT Support',
                'deskripsi'            => 'Memberikan dukungan teknis dan pemeliharaan sistem jaringan.',
                'tanggal_mulai_magang' => now()->addDays(29),
                'deadline_lowongan'    => now()->addDays(18),
                'lokasi'               => 'Jakarta',
                'perusahaan_id'        => 9,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_it_support.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2400000,
                'kuota'                => 4,
            ],
            [
                'judul'                => 'Magang Cloud Infrastructure',
                'deskripsi'            => 'Mempelajari setup dan manajemen infrastruktur cloud (AWS/GCP).',
                'tanggal_mulai_magang' => now()->addDays(21),
                'deadline_lowongan'    => now()->addDays(11),
                'lokasi'               => 'Makassar',
                'perusahaan_id'        => 10,
                'periode_id'           => 1,
                'sylabus_path'         => 'sylabus/magang_cloud_infra.pdf',
                'status'               => 'aktif',
                'gaji'                 => 3600000,
                'kuota'                => 2,
            ],
            [
                'judul'                => 'Magang Network Engineer',
                'deskripsi'            => 'Membantu pengaturan dan pemeliharaan jaringan perusahaan.',
                'tanggal_mulai_magang' => now()->addDays(31),
                'deadline_lowongan'    => now()->addDays(16),
                'lokasi'               => 'Makassar',
                'perusahaan_id'        => 10,
                'periode_id'           => 2,
                'sylabus_path'         => 'sylabus/magang_network_engineer.pdf',
                'status'               => 'aktif',
                'gaji'                 => 2500000,
                'kuota'                => 3,
            ],
        ];

        DB::table('t_lowongan_magang')->insert($data);
    }
}
